let loaded_matchparen = 1
filetype indent on
filetype plugin on
set autoindent
set autoread
set backspace=indent,eol,start
set cmdheight=1
set colorcolumn=80
set completeopt=menuone,noinsert,noselect
set encoding=utf-8
set exrc
set fileformats=unix,mac,dos
set guicursor=
set hidden
set hlsearch
set history=1000
set incsearch
set ignorecase
set mouse=a
set nobackup
set nocompatible
set noerrorbells
set noexpandtab
set noswapfile
set novisualbell
set nowrap
set nowritebackup
set number
set pastetoggle=<F11>
set relativenumber
set regexpengine=1
set report=0
set ruler
set scrolloff=8
set shell=/bin/bash
set shiftwidth=4
set shortmess+=c
set showcmd
set showmatch
set showmode
set signcolumn=yes
set smartcase
set smartindent
set softtabstop=4
set splitbelow
set splitright
set t_Co=256
set tabstop=4
set termguicolors
set title
set ttyfast
set undolevels=1000
set updatetime=50
set wildchar=<TAB>
set wildignore+=*.DS_STORE,*.db,node_modules/**
set wildignore+=*.docx,*.jpg,*.png,*.gif,*.pdf,*.pyc,*.exe,*.flv,*.img,*.xlsx
set wildignore+=*/.git/*,*/.hg/*,*/.svn/*,*/node_modules/*
set wildignore+=*/coverage
set wildmenu
set wildmode=list:longest
set wrapscan
syntax on
colorscheme slate
